# AUTOGENERATED FROM 'app/queries/participant/delete_participant.edgeql' WITH:
#     $ edgedb-py --dir app/queries/participant --no-skip-pydantic-validation


from __future__ import annotations

import dataclasses
import uuid
from typing import cast

import edgedb


@dataclasses.dataclass
class DeleteParticipantResult:
    id: uuid.UUID


async def delete_participant(
    executor: edgedb.AsyncIOExecutor,
    *,
    participant_id: uuid.UUID,
) -> DeleteParticipantResult | None:
    return cast(
        DeleteParticipantResult,
        await executor.query_single(
            """\
        with
            participant_id := <uuid>$participant_id
        delete Participant filter .id = participant_id;\
        """,
            participant_id=participant_id,
        ),
    )
