# AUTOGENERATED FROM 'app/queries/participant_date/star.edgeql' WITH:
#     $ edgedb-py --dir app/queries/participant_date --no-skip-pydantic-validation


from __future__ import annotations

import dataclasses
import uuid
from typing import cast

import edgedb


@dataclasses.dataclass
class StarResult:
    id: uuid.UUID


async def star(
    executor: edgedb.AsyncIOExecutor,
    *,
    participant_date_id: uuid.UUID,
) -> StarResult | None:
    return cast(
        StarResult,
        await executor.query_single(
            """\
        with
            participant_date_id := <uuid>$participant_date_id,
        update
            ParticipantDate
            filter .id = participant_date_id
            set {starred := true, enabled := true};\
        """,
            participant_date_id=participant_date_id,
        ),
    )
