# AUTOGENERATED FROM 'app/queries/participant_date/turn_on_participant_date.edgeql' WITH:
#     $ edgedb-py --dir app/queries/participant_date --no-skip-pydantic-validation


from __future__ import annotations

import dataclasses
import uuid
from typing import cast

import edgedb


@dataclasses.dataclass
class TurnOnParticipantDateResult:
    id: uuid.UUID


async def turn_on_participant_date(
    executor: edgedb.AsyncIOExecutor,
    *,
    participant_date_id: uuid.UUID,
) -> TurnOnParticipantDateResult | None:
    return cast(
        TurnOnParticipantDateResult,
        await executor.query_single(
            """\
        with
            participant_date_id := <uuid>$participant_date_id,
        update ParticipantDate
        filter .id = participant_date_id
        set {enabled := true};\
        """,
            participant_date_id=participant_date_id,
        ),
    )
